name: 'Metis Test Suite'
description: 'Create metis test session'
inputs:
  metis_api_key:
    description: metis api key project identifier
    required: true
    default: ''
  github_token:
    description: github token
    required: true
    default: ''
  target_url:
    description: target url
    required: false
    default: ''
outputs:
  pr_tag: # id of output
    description: 'the tag pr value'
runs:
  using: 'node16'
  main: 'dist/index.js'
  post: dist/post.js
